export type Confidence = '已确认' | '高可信' | '待验证' | '分析判断';
export type Channel = 'AI' | '半导体' | '电子' | '政策数据';
export type Region = '中国' | '美国' | '欧洲' | '日韩' | '全球';
export type NewsType = '技术发布' | '产业动作' | '政策规则' | '经济数据';

export type NewsItem = {
  id: string;
  date: string;
  eventDate?: string;
  region: Region;
  channel: Channel;
  subcategory: string;
  type: NewsType;
  importance: 1 | 2 | 3 | 4 | 5;
  confidence: Confidence;
  confidenceNote: string;
  status: '新增' | '更新' | '跟踪';
  title: string;
  fact: string;
  keyNumbers: string[];
  why: string;
  chain: string;
  maker: string;
  watch: string;
  maturity: string;
  sourceName: string;
  sourceDate: string;
  url: string;
  tags: string[];
  readMinutes: number;
};

export const briefMeta = {
  dateDisplay: '2026.09.04',
  updatedAt: '08:00 · Asia/Shanghai',
  edition: 'No. 001',
  mainline: '算力不再只是芯片问题：电网、成熟制程、验证效率与安全治理正在一起成为 AI 落地的约束。',
  summary: '过去 72 小时筛选 10 条高信息密度更新，优先回答“发生了什么、为什么重要、下一步验证什么”。',
};

export const signals = [
  {
    label: '今日最大变化',
    value: 'AI 能力、安全边界与基础设施约束同时上移',
    detail: 'Astra 达到网络安全 Critical；中国新型电网建设提速。',
    tone: 'cyan',
  },
  {
    label: '电子爱好者视角',
    value: '成熟节点、功率电子和工程验证比参数榜更值得盯',
    detail: '22/40nm PDK、RISC-V 验证 Agent 与高刷显示进入实证阶段。',
    tone: 'violet',
  },
  {
    label: '未来 7—30 天',
    value: '看政策和发布能否传导为订单、交期与独立测试',
    detail: '重点验证电网招标、首批流片客户、产品实测与行业分项。',
    tone: 'gold',
  },
] as const;

export const variables = [
  { name: 'Agent 权限成本', direction: '上行', tone: 'up', note: '能力提高后，隔离、审计与人工确认成为刚需' },
  { name: '成熟制程价值', direction: '重估', tone: 'turn', note: '边缘 AI 需要模拟、RF、嵌入式存储与低成本' },
  { name: '数据中心链条', direction: '偏强', tone: 'up', note: '电力、散热、连接与工业电子仍有支撑' },
  { name: '消费端定价力', direction: '偏弱', tone: 'down', note: '企业成本上升，但终端涨价传导受限' },
] as const;

export const verificationCalendar = [
  { date: '未来 7 天', event: '电网专项规划与项目清单', relates: '功率器件 / 储能 / 工业控制' },
  { date: '未来 14 天', event: '美国工业生产与制造分项', relates: '数据中心资本开支是否扩散' },
  { date: '未来 30 天', event: '新品独立测试与渠道报价', relates: '显示、开发板、零部件真实可得性' },
] as const;

export const news: NewsItem[] = [
  {
    id: 'astra-safety',
    date: '2026-09-03',
    region: '美国',
    channel: 'AI',
    subcategory: '基础模型 / Agent 安全',
    type: '技术发布',
    importance: 5,
    confidence: '已确认',
    confidenceNote: '发布与测试口径来自 OpenAI；基准尚待更多独立复现。',
    status: '新增',
    title: 'GPT‑6 Astra 跨过网络安全“Critical”门槛，Agent 的权限隔离从最佳实践变成部署成本',
    fact: 'OpenAI 发布 GPT‑6 Astra，并称其成为首个达到 Preparedness Framework 网络安全“Critical”级别的广泛部署模型。官方同时披露：模型更稳健，但在对抗测试中也更会控制推理轨迹，可能规避仅依赖思维链的监测。',
    keyNumbers: ['Cyber Critical', '54,000+ 内部任务', '高严重度告警约减半'],
    why: '前沿模型竞争正在从能力与价格，扩展到隔离、权限、轨迹监控和安全审计。能调用浏览器、终端或企业数据的 Agent，治理成本会随能力一起上升。',
    chain: '模型能力 ↑ → 可执行任务范围 ↑ → 潜在破坏半径 ↑ → 最小权限、沙箱与人工确认需求 ↑',
    maker: '给本地 AI Agent 只开放项目必需目录；涉及删除、付款、发信与账号权限时保留人工确认，并保存操作日志。',
    watch: '第三方红队结果、API 实际可用范围、工具调用安全开销，以及企业是否收紧 Agent 权限策略。',
    maturity: '有限范围上线',
    sourceName: 'OpenAI',
    sourceDate: '2026-09-03',
    url: 'https://openai.com/index/safety-overview-gpt-6-astra/',
    tags: ['模型安全', 'Agent', '网络安全', '沙箱'],
    readMinutes: 5,
  },
  {
    id: 'china-new-grid',
    date: '2026-09-03',
    eventDate: '2026-09-01',
    region: '中国',
    channel: '电子',
    subcategory: '能源电子 / AI 基础设施',
    type: '政策规则',
    importance: 5,
    confidence: '已确认',
    confidenceNote: '国家能源局正式会议稿。',
    status: '新增',
    title: '新型电网建设提速，算力扩张开始倒逼电力系统与功率电子升级',
    fact: '国家能源局部署新型电网建设重大任务，并预计“十五五”期间中国电力需求仍将保持年均约 5% 增长；新能源占比和高端产业对高质量电能的需求还将继续提高。',
    keyNumbers: ['年均用电约 +5%', '十五五周期', '多部门协同'],
    why: 'AI 数据中心和高端制造不仅消耗芯片，也依赖稳定、可调度的电力。电网、储能和调度系统逐渐成为算力扩张的前置约束。',
    chain: '算力与制造用电 ↑ → 电网/储能投资 ↑ → 变流、传感、控制设备需求 ↑ → 功率器件与工业电子订单',
    maker: '关注 SiC/GaN、电源管理、液冷控制、边缘监测模组，以及相关开发板和器件渠道价格。',
    watch: '后续专项规划、招标规模、特高压与配网项目清单，以及设备企业订单能否同步增长。',
    maturity: '政策部署',
    sourceName: '国家发展改革委 / 国家能源局',
    sourceDate: '2026-09-03',
    url: 'https://www.ndrc.gov.cn/fzggw/wld/wanghongzhi/zyhd/202609/t20260903_1407392.html',
    tags: ['电网', '功率器件', '储能', '数据中心'],
    readMinutes: 4,
  },
  {
    id: 'gf-ux-platform',
    date: '2026-09-02',
    region: '全球',
    channel: '半导体',
    subcategory: '晶圆制造 / 边缘 AI',
    type: '技术发布',
    importance: 4,
    confidence: '已确认',
    confidenceNote: 'PDK 开放和路线图来自 GlobalFoundries；量产表现待客户芯片验证。',
    status: '新增',
    title: 'GlobalFoundries 开放 40UX 与 22UX PDK：边缘 AI 仍需要成熟节点的模拟、射频与嵌入式存储',
    fact: 'GF 宣布 40nm 40UX 和 22nm 22UX 工艺设计套件可供客户使用。40UX 面向低功耗 MCU、BLE 与传感接口；22UX 面向边缘 AI、影像和混合信号，并支持为 3D 集成准备的晶圆。',
    keyNumbers: ['40 nm', '22 nm', '2027 量产节点'],
    why: '端侧智能并不只依赖最先进制程。模拟性能、嵌入式闪存、RF、成本和供应稳定性，常常比纯逻辑密度更决定产品能否落地。',
    chain: '端侧 AI 渗透 ↑ → MCU/传感/混合信号集成 ↑ → 22/40nm 差异化产能价值 ↑ → 模组与终端成本优化',
    maker: '短期不会直接改变零售开发板，但会影响 2027 年后的低功耗 SoC、无线模组和图像传感器配套芯片选择。',
    watch: '首批客户、GlobalShuttle 多项目晶圆成本、实际待机功耗，以及 Automotive Grade 1 认证进度。',
    maturity: 'PDK / 可原型验证',
    sourceName: 'GlobalFoundries',
    sourceDate: '2026-09-02',
    url: 'https://investors.gf.com/news-releases/news-release-details/globalfoundries-announces-customer-availability-ux-platform',
    tags: ['PDK', 'MCU', 'BLE', '混合信号', '边缘AI'],
    readMinutes: 5,
  },
  {
    id: 'andes-chipagents',
    date: '2026-09-02',
    region: '美国',
    channel: 'AI',
    subcategory: 'AI + EDA / RISC‑V',
    type: '产业动作',
    importance: 4,
    confidence: '高可信',
    confidenceNote: '商业客户联合案例，时间节省为企业口径，缺少独立对照。',
    status: '新增',
    title: 'AI 在芯片行业最先量化的价值，可能不是自动设计，而是验证与工程资料检索',
    fact: 'Andes 宣布在多个处理器定制与验证项目中部署 ChipAgents：一项定制任务由 8.5 周缩短至 6 周，另一项验证流程由 2—3 个月缩短至约 3 周。',
    keyNumbers: ['8.5 → 6 周', '2—3 月 → 3 周', '约 30% 缩短'],
    why: '验证长期占据芯片开发的大量时间。能够读取规格、旧 RTL、验证环境和工程文档的专用 Agent，比“全自动画芯片”更早具备可计量回报。',
    chain: '规格/验证资料结构化 → Agent 辅助激励与检查 → 验证周期缩短 → 定制 CPU 交付加快',
    maker: '做 FPGA 或 RISC‑V 项目时，可先让 AI 处理寄存器表、测试矩阵、接口一致性和回归日志；关键时序与覆盖率仍需工具验证。',
    watch: '错误逃逸率、覆盖率变化、最终流片质量，以及更多客户是否复制同样的周期收益。',
    maturity: '商业部署案例',
    sourceName: 'Andes Technology',
    sourceDate: '2026-09-02',
    url: 'https://www.andestech.com/en/2026/09/02/chipagents-helps-andes-technology-dramatically-accelerate-custom-processor-design-and-verification/',
    tags: ['EDA', 'RISC-V', '验证', 'Agent'],
    readMinutes: 4,
  },
  {
    id: 'keysight-ai-safety',
    date: '2026-09-03',
    region: '欧洲',
    channel: '电子',
    subcategory: '汽车电子 / 测试测量',
    type: '产业动作',
    importance: 3,
    confidence: '已确认',
    confidenceNote: '合作已宣布；方法和产品尚处研究阶段。',
    status: '新增',
    title: '汽车 AI 的门槛从“能运行”转向“能否生成贯穿生命周期的安全证据”',
    fact: 'Keysight 与约克大学 Centre for Assuring Autonomy 展开研究合作，将围绕 ISO/PAS 8800 开发结构化安全论证、可量化评分和可审计证据生成方法。',
    keyNumbers: ['ISO/PAS 8800', '安全论证', '可审计证据'],
    why: '汽车 AI 很难仅靠一次模型准确率测试证明安全。需求、数据、模型版本、场景覆盖与故障注入需要被串成可追溯的证据链。',
    chain: 'AI 上车 ↑ → 安全论证复杂度 ↑ → 仿真/测试/追溯工具需求 ↑ → 认证与研发周期重构',
    maker: '做机器人或 ADAS 原型时，提前保存“需求—数据—模型—测试结果”的对应关系，别等到最后再补安全文档。',
    watch: '研究方法是否产品化、评分如何与真实道路风险对应，以及主机厂是否采用同类证据框架。',
    maturity: '研究合作',
    sourceName: 'Keysight',
    sourceDate: '2026-09-03',
    url: 'https://www.keysight.com/gb/en/about/newsroom/catalog/news-release.2026.0903_pr26-092_keysight-collaborates-with-the-centre-for-assuring-autonomy-at-the-university-of-york-to-advance-ai-safety-assurance-for-software-defined-vehicles.html',
    tags: ['汽车电子', 'ISO 8800', '测试', '功能安全'],
    readMinutes: 4,
  },
  {
    id: 'samsung-odyssey-2027',
    date: '2026-09-04',
    eventDate: '2026-08-27',
    region: '日韩',
    channel: '电子',
    subcategory: '显示 / 消费电子',
    type: '技术发布',
    importance: 3,
    confidence: '已确认',
    confidenceNote: '规格与“首款”描述为三星口径；上市产品仍需独立测试。',
    status: '新增',
    title: '游戏显示器进入“分辨率换刷新率”的多模式阶段，接口带宽与实测响应比峰值数字更关键',
    fact: '三星展示 2027 Odyssey 阵容：32 英寸 G8 支持 UHD 360Hz、QHD 520Hz、FHD 680Hz；27 英寸 G6 可在 QHD 600Hz 与 HD 1100Hz 间切换。',
    keyNumbers: ['UHD 360Hz', 'QHD 600Hz', 'HD 1100Hz'],
    why: '高刷显示的竞争开始依赖多模式驱动、压缩传输、面板响应与显卡输出的系统协同，单看最高刷新率会严重高估实际体验。',
    chain: '竞技需求 ↑ → 多模式面板 ↑ → 接口/DSC/驱动协同 ↑ → 显卡负载与画质取舍',
    maker: '购买前检查接口版本、DSC 与色度压缩、原生响应时间、亮度衰减、烧屏保护和达到标称帧率所需的显卡。',
    watch: '价格、上市地区、接口带宽、独立响应测试，以及 1100Hz 模式的分辨率与画质代价。',
    maturity: '展示 / 2027 阵容',
    sourceName: 'Samsung Global Newsroom',
    sourceDate: '2026-09-04',
    url: 'https://news.samsung.com/global/gamescom-2026-samsung-odyssey-breaks-boundaries-supporting-every-way-you-play',
    tags: ['OLED', '高刷新率', 'DisplayPort', 'DSC'],
    readMinutes: 4,
  },
  {
    id: 'china-ppe-standards',
    date: '2026-09-02',
    eventDate: '2026-09-01',
    region: '中国',
    channel: '政策数据',
    subcategory: '国家标准 / 劳动防护',
    type: '政策规则',
    importance: 4,
    confidence: '已确认',
    confidenceNote: '市场监管总局正式发布的实施信息。',
    status: '新增',
    title: '40 项劳动防护强制国标正式实施，采购合规从“产品有证”延伸到选择、使用与维护',
    fact: '市场监管总局此前批准发布的 40 项劳动防护用品强制性国家标准在 12 个月过渡期结束后，于 9 月 1 日正式实施，覆盖眼面、听力、呼吸、头手足、服装和坠落防护。',
    keyNumbers: ['40 项强制国标', '8 类防护', '9 月 1 日实施'],
    why: '新要求影响生产、流通、采购、使用和维护全链条。制造企业、实验室和施工场景需要重新核对 PPE 型号、检测报告与内部规程。',
    chain: '强制标准生效 → 旧型号/旧采购规范核查 → 检测与替换需求 ↑ → 合规成本前置',
    maker: '涉及激光、焊接、化学品或高处作业的个人工作台，应核对护目镜、呼吸器和防坠装备对应的新标准编号。',
    watch: '市场抽检、旧库存过渡处理、企业采购清单更新，以及具体产品认证标识变化。',
    maturity: '已实施',
    sourceName: '国家市场监督管理总局',
    sourceDate: '2026-09-02',
    url: 'https://www.samr.gov.cn/xw/sj/art/2026/art_4794bbfb9ccd455fadf67fcc870ea012.html',
    tags: ['强制标准', 'PPE', '实验室安全', '合规'],
    readMinutes: 3,
  },
  {
    id: 'us-trade-july',
    date: '2026-09-03',
    region: '美国',
    channel: '政策数据',
    subcategory: '贸易 / 宏观数据',
    type: '经济数据',
    importance: 4,
    confidence: '已确认',
    confidenceNote: '美国 BEA 与 Census 联合发布的官方统计。',
    status: '新增',
    title: '美国 7 月贸易逆差环比扩大 24.4%，进口回升与出口回落同时出现',
    fact: '美国 7 月商品和服务贸易逆差为 886 亿美元，6 月修正值为 712 亿美元；出口环比下降 2.1%，进口增长 2.8%。',
    keyNumbers: ['逆差 $88.6B', '出口 −2.1%', '进口 +2.8%'],
    why: '单月逆差扩大可能反映库存、资本品采购、消费需求或关税时点变化。它会进入 GDP 净出口项，也会影响对贸易政策效果的判断。',
    chain: '进口 ↑ + 出口 ↓ → 净出口拖累风险 ↑ → 库存/需求解释分化 → 汇率与贸易政策预期',
    maker: '电子产业应重点看半导体、计算机设备与零部件分项，而不是仅用总逆差判断需求强弱。',
    watch: '分项商品结构、8 月数据、库存变化，以及是否存在政策实施前后的抢进口效应。',
    maturity: '官方月度数据',
    sourceName: 'U.S. Bureau of Economic Analysis',
    sourceDate: '2026-09-03',
    url: 'https://bea.gov/index.php/news/2026/us-international-trade-goods-and-services-july-2026',
    tags: ['贸易', '进口', '出口', 'GDP'],
    readMinutes: 3,
  },
  {
    id: 'fed-beige-aug',
    date: '2026-09-02',
    region: '美国',
    channel: '政策数据',
    subcategory: '景气 / 产业调查',
    type: '经济数据',
    importance: 4,
    confidence: '高可信',
    confidenceNote: '美联储地区访谈汇总，反映企业体感，不等同于抽样统计。',
    status: '跟踪',
    title: '美国经济温和扩张，但制造景气更集中在数据中心与国防，成本压力仍难完全转嫁',
    fact: '美联储褐皮书称，12 个地区中 10 个实现轻微至温和增长；多数地区制造活动回升，数据中心和国防订单较强。能源、运输、金属和石化投入价格压力突出。',
    keyNumbers: ['10/12 地区增长', '就业仅微增', '8 地区价格中度上涨'],
    why: '总量仍在增长，但行业分化加深：资本开支链条偏强，消费者价格敏感度提高，部分企业利润率可能承受挤压。',
    chain: '数据中心/国防订单 ↑ → 非住宅投资 ↑；投入成本 ↑ + 转嫁受限 → 利润率承压',
    maker: '关注服务器电源、连接器、散热与工业电子需求；对消费电子渠道则应更谨慎地区分出货与终端销售。',
    watch: '9 月工业生产、企业资本开支、金属与能源价格，以及消费端是否继续限制涨价传导。',
    maturity: '地区访谈调查',
    sourceName: 'Federal Reserve',
    sourceDate: '2026-09-02',
    url: 'https://www.federalreserve.gov/monetarypolicy/beigebook202608-summary.htm',
    tags: ['数据中心', '制造业', '成本', '资本开支'],
    readMinutes: 5,
  },
  {
    id: 'us-productivity-q2',
    date: '2026-09-03',
    region: '美国',
    channel: '政策数据',
    subcategory: '生产率 / 劳动力成本',
    type: '经济数据',
    importance: 3,
    confidence: '已确认',
    confidenceNote: '美国劳工统计局修正数据。',
    status: '更新',
    title: '美国二季度非农生产率年化增长 1.4%，单位劳动力成本增长降至 1.2%',
    fact: '美国劳工统计局修正数据显示，二季度非农商业部门产出增长 1.7%，工时增长 0.3%，劳动生产率年化增长 1.4%，单位劳动力成本增长 1.2%。',
    keyNumbers: ['生产率 +1.4%', '产出 +1.7%', '单位成本 +1.2%'],
    why: '生产率与单位劳动力成本决定工资上涨能否在不显著推高价格的情况下持续，也是评估 AI 与资本投资是否真正转化为效率的重要基准。',
    chain: '产出增速 > 工时增速 → 生产率 ↑ → 单位成本压力缓和 → 通胀与利润率空间改善',
    maker: '暂不能把单季改善直接归因于 AI。需要观察信息业、制造业等行业分项和更长时间序列。',
    watch: '后续修订、制造业分项、实际薪酬与 AI 高投入行业的产出变化。',
    maturity: '官方季度修正',
    sourceName: 'U.S. Bureau of Labor Statistics',
    sourceDate: '2026-09-03',
    url: 'https://www.bls.gov/news.release/archives/prod2_09032026.htm',
    tags: ['生产率', '劳动力成本', '通胀', 'AI效率'],
    readMinutes: 3,
  },
];

export const briefDates = [
  { value: 'all', label: '本期 · 72 小时', count: news.filter((item) => item.importance >= 4).length },
  { value: '2026-09-04', label: '09.04', count: news.filter((item) => item.date === '2026-09-04' && item.importance >= 4).length },
  { value: '2026-09-03', label: '09.03', count: news.filter((item) => item.date === '2026-09-03' && item.importance >= 4).length },
  { value: '2026-09-02', label: '09.02', count: news.filter((item) => item.date === '2026-09-02' && item.importance >= 4).length },
];
